<a href="https://colab.research.google.com/github/priyansh-commits/Deep_Learning/blob/main/grad_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import time

In [3]:
df=pd.read_csv('/content/placement.csv')
df.head(5)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [17]:
X=df.iloc[:,0]
y=df.iloc[:,-1]

In [16]:
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ...
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X.values.reshape(-1, 1))

In [22]:
X_scaled=pd.DataFrame(X_scaled)
X_scaled.shape

(200, 1)

In [23]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [24]:
model=Sequential()
model.add(Dense(1,activation='linear',input_dim=1))
model.add(Dense(2,activation='relu',input_dim=1))
model.add(Dense(1,activation='linear',input_dim=1))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │             4 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(
    optimizer='adam',
    loss='mse',  # Loss function for training
    metrics=['mse', 'mae']  # Metrics for monitoring
)
start = time.time()
history = model.fit(X_scaled,y,epochs=10,batch_size=1,validation_split=0.2)
print(time.time() - start)

Epoch 1/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.1091 - mae: 0.2595 - mse: 0.1091 - val_loss: 0.1069 - val_mae: 0.2730 - val_mse: 0.1069
Epoch 2/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1093 - mae: 0.2591 - mse: 0.1093 - val_loss: 0.1074 - val_mae: 0.2734 - val_mse: 0.1074
Epoch 3/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1094 - mae: 0.2611 - mse: 0.1094 - val_loss: 0.1038 - val_mae: 0.2709 - val_mse: 0.1038
Epoch 4/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1099 - mae: 0.2601 - mse: 0.1099 - val_loss: 0.1035 - val_mae: 0.2700 - val_mse: 0.1035
Epoch 5/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1098 - mae: 0.2595 - mse: 0.1098 - val_loss: 0.1047 - val_mae: 0.2711 - val_mse: 0.1047
Epoch 6/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1088 - mae: 0.2589 - mse: 0.1088 - val_loss: 0.1062 - val_mae: 0.2725 - val_mse: 0.1062
Epoch 7/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1101 - mae: 0.2599 - mse: 0.1101 - val_loss: 0.1070 - val_mae: 0.2731 - val_mse: 0.1070
Epoch 8/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1092 - mae: 0.2580 - mse: 0.1092 - val_loss: 0.1067 - val_mae: 0.2728 - val_mse: 0.1067
Epoch 9/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1101 - mae: 0.2618 - mse: 0.1101 - val_loss: 0.1045 - val_mae: 0.2709 - val_mse: 0.1045
Epoch 10/10
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1099 - mae: 0.2580 - mse: 0.1099 - val_loss: 0.1085 - val_mae: 0.2745 - val_mse: 0.1085
6.382092475891113

In [31]:
y_pred=model.predict(y)
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y, y_pred))
print('MSE:', metrics.mean_squared_error(y, y_pred))

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
MAE: 1.823272279691696
MSE: 3.3935504915352244